# Generated by Django 5.1.2 on 2024-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_postagem_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(default='Título Padrão', max_length=255),
        ),
    ]
