# Generated by Django 5.1.2 on 2024-12-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tarefa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_limite',
        ),
    ]
